# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 06:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('title1', models.CharField(max_length=50, verbose_name='oonvan dastan')),
                ('matn', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='matn')),
                ('URL_Field', models.URLField(null=True, verbose_name='url')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nevisandeh')),
            ],
        ),
    ]
