# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='URL_Field',
        ),
    ]
