# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_story_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='filefield',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
