# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_story_filefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='filefield',
        ),
    ]
